let resumeData = {
    "imagebaseurl":"https://donaldarango.github.io/",
    "name": "Donny Arango",
    "role": "Game Programmer",
    "socialLinks":[
        {
          "name":"linkedin",
          "url":"https://www.linkedin.com/in/donaldarango/",
          "className":"fa fa-linkedin"
        },
        {
          "name":"github",
          "url":"https://github.com/donaldarango",
          "className":"fa fa-github"
        },
      ],
    "aboutme":"I am a passionate, team-oriented game programmer with a strong background in C++ and a deep love for everything games. I started my software engineering journey as a web developer, but quickly found my true passion lies in game development. The complexity of the problems and the creativity involved in making games is like no other field, and this is what drives me to keep learning and improving my skills. Multiplayer games are my favorite to play, as I love the social and community aspects that come along with them. Check out my latest project Mythbound, which is the first multiplayer game I've worked on and is currently in development!",
    "portfolio":[
      {
        "id":"Mythbound",
        "name":"Mythbound",
        "teamSize": "17",
        "cardImgurl":"images/portfolio/Mythbound/MythboundBanner.png",
        "bannerImgurl":"",
        "bannerVideourl":"images/portfolio/Mythbound/MythboundGameplay.webp",
        "logoImgurl":"images/portfolio/Mythbound/MythboundLogo.png",  
        "tags":["Unreal 5", "C++", "Multiplayer", "Blueprints"],  
        "fullDescription":"Mythbound is a multiplayer arena brawler developed as the capstone project for my graduate degree in interactive entertainment. The game features fast-paced combat, a variety of characters with unique abilities, and exciting game modes. This is the first multiplayer game that I have developed, and while challenging, the creation of this game has been one of the most rewarding experiences of my career thus far.",
        "startDate":"10/2025",
        "endDate":"Present",
        "role":"Gameplay Programmer",
        "developer": "Skaldforge",
        "link_url":"",
        "github_url":"",
      },
      {
        "id":"SlayTheSpire",
        "name":"Slay The Spire C++",
        "teamSize": "5",
        "cardImgurl":"images/portfolio/SlayTheSpire/STSBanner.png",
        "bannerVideourl":"images/portfolio/SlayTheSpire/STSGameplay.mp4",
        "logoImgurl":"images/portfolio/SlayTheSpire/STSLogo.png",
        "tags":["C++", "Custom Engine", "JSON", "Raylib"],
        "fullDescription":"This Slay The Spire clone was created as a group project in 3 weeks to cap off the completion of a custom C++ game engine that was developed over the course of a semester. While I cannot give too many details about the engine here, due to limiting the information available online for future students, I would love to chat about the technical details in person! This game features the main battle gameplay loop of Slay The Spire, including card-based combat, enemy encounters, and character progression systems.",
        "startDate":"04/2026",
        "endDate":"05/2026",
        "role":"Gameplay Programmer",
      },
      {
        "id": "Archon",
        "name": "Archon C Remake",
        "teamSize": "Solo",
        "role":"Gameplay Programmer",
        "cardImgurl":"images/portfolio/Archon/Archon.png",
        "bannerVideourl":"images/portfolio/Archon/ArchonGameplay.mp4",
        "logoImgurl":"images/portfolio/Archon/ArchonLogo.png",
        "tags":["C", "OpenGL", "Local Co-op"],
        "startDate":"11/2025",
        "endDate":"12/2025",

        "fullDescription": "This is a remake of the classic 1983 game Archon: The light and the dark. The game is a chess-like strategy game where players control pieces that have different abilities and stats. The game features a board state where players can move their pieces around and an arena state where players can engage in combat when their pieces occupy the same space on the board. The game was built using C and OpenGL and was a great learning experience for me in terms of understanding the fundamentals of game development and graphics programming.",
      },
      {
        "id":"PaintingPanic",
        "name":"Painting Panic",
        "teamSize": "Solo",
        "cardImgurl":"images/portfolio/RayTracer/PaintingPanic.png",
        "bannerVideourl":"images/portfolio/RayTracer/PaintingPanicBanner.mp4",
        "logoImgurl":"images/portfolio/RayTracer/Opengl-logo.svg",
        "tags":["68k Assembly", "Local Co-op"],
        "fullDescription":"",
        "startDate":"10/2025",
        "endDate":"10/2025",
        "link_url":"",
      },
      {
        "id":"RayTracer",
        "name":"OpenGL Ray Tracer",
        "teamSize": "2",
        "cardImgurl":"images/portfolio/RayTracer/RayTracerPerspective.png",
        "bannerVideourl":"images/portfolio/RayTracer/RayTracerBanner.mp4",
        "logoImgurl":"images/portfolio/RayTracer/Opengl-logo.svg",
        "tags":["C++", "Graphics", "OpenGL"],
        "fullDescription":"This was my first project using OpenGL and was my introduction into the world of graphics programming. It is a basic ray tracer that supports rendering spheres, planes, and triangles along with configurable lighting and materials. The objects themselves are defined by their geometric properties and material attributes. The project was built using C++ and OpenGL and was a great learning experience for me in terms of understanding the fundamentals of graphics programming.",
        "startDate":"02/2024",
        "endDate":"03/2024",
        "link_url":"",
        "github_url":"https://github.com/donaldarango/Raytracer",
      },
      {
        "id":"ObjViewer",
        "name":"OBJ File Viewer",
        "teamSize": "2",
        "cardImgurl":"images/portfolio/OBJFileViewer/OBJFileViewer.png",
        "bannerVideourl":"images/portfolio/OBJFileViewer/OBJFileViewerBanner.mp4",
        "logoImgurl":"images/portfolio/OBJFileViewer/OBJFileViewerLogo.png",
        "tags":["C++", "Graphics", "OpenGL"],
        "fullDescription":"",
        "startDate":"03/2024",
        "endDate":"04/2024",
        "link_url":"",
        "github_url":"https://github.com/donaldarango/3D-Model-Viewer",
      },
      {
        "id":"Shardhold",
        "name":"Shardhold",
        "teamSize": "5",
        "cardImgurl":"images/portfolio/Shardhold/ShardholdCard.png",
        "bannerVideourl":"images/portfolio/Shardhold/ShardholdGameplay.gif",
        "logoImgurl":"",
        "tags":["Unity", "C#", "JSON"],
        "fullDescription":"Shardhold is a turn-based card strategy game where players defend their home tree from waves of robot enemies trying to destroy it. This project was one my first games to be co-developed and was built in Unity as a Senior capstone project for my undergraduate degree. ",
        "startDate":"01/2025",
        "endDate":"04/2025",
        "role":"Gameplay Programmer",
        "link_url":"",
        "github_url":"https://github.com/donaldarango/Shardhold",
      },
    ],
  }
  
  export default resumeData